name: Build and Test app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development
      - storage_revamp_baseline

jobs:
  build:
    runs-on: [macos-latest]

    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          action: build test
          build-settings: ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES
          configuration: Debug
          derived-data-path: "${{github.workspace}}/SplitApp"
          destination: 'platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro Max'
          project: Split.xcodeproj
          scheme: Split
          sdk: 'iphonesimulator'
          use-xcpretty: true

      - name: SonarQube Install
        uses: mathrix-education/sonar-scanner@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          version: 4.6.2.2472
          scan: false

      - name: SonarQube Scan
        run: >
          sonar-scanner --debug
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} 
          -Dsonar.projectName=${{ github.event.repository.name }} 
          -Dsonar.projectKey=splitio_ios-client 
          -Dsonar.github.token=${{ secrets.GITHUB_TOKEN }} 
          -Dsonar.c.file.suffixes=- 
          -Dsonar.cpp.file.suffixes=- 
          -Dsonar.objc.file.suffixes=-
