name: Build xcframework

on:
  push:
    branches: 
      - test_xcframework*
    #tags:
      #- *.*.*

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.0

    - name: Checkout
      uses: actions/checkout@v2

#     - name: Create xcframework for release
#       run: ./gen_static_xcframework

    - name: Check tag type and add it to env
      run: echo "release_type=$(./check_tag_type ${{ github.ref }})" >> $GITHUB_ENV; echo "release_type=$(./check_tag_type ${{ github.ref }})"
      
    - uses: chrislennon/action-aws-cli@v1.1    
    - if: ${{ env.release_type == 1 }}
      run: |
        echo "type release stable: ${{ env.release_type }}"
#       run: aws s3 cp ./Split_XCFramework/Split.xcframework s3://aws-development-split-public/mobile/ios-xcframework --recursive
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  
    - if: ${{ env.release_type == 0 }}
      run: |
        echo "type release candidate: ${{ env.release_type }}"
#       run: aws s3 cp ./Split_XCFramework/Split.xcframework s3://aws-development-split-public/mobile/ios-xcframework --recursive
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
